#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run test

files=`git diff --name-only --staged --diff-filter=ACM src/`
if [[ ${#files[@]} -gt 0 ]]; then
  npx prettier --write $files
  git add $files
fi

exit 0